# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOC8iUyVVQtQL-FXYqipLxG_aBs1ZYqS
"""

import pandas as pd
import numpy as np

print("¡Librerías importadas con éxito! Listo para trabajar con los datos.")

df = pd.read_csv('catalogo_limpio.csv')

df.info()

# Comprobamos si hay filas duplicadas
duplicados = df.duplicated().sum()
print(f"Número de filas duplicadas: {duplicados}")

# Eliminamos las filas duplicadas
df = df.drop_duplicates()

# Comprobamos cuántas filas nos quedan ahora
print(f"Número de filas después de limpiar duplicados: {len(df)}")

# Normalizamos las columnas de texto (quitamos espacios y dejamos en minúsculas por si acaso)
df['categoria_original'] = df['categoria_original'].astype(str).str.strip().str.lower()
df['categoria_traducida'] = df['categoria_traducida'].astype(str).str.strip().str.lower()

print("¡Cadenas de texto normalizadas con éxito!")

# Resumen estadístico de las columnas numéricas
df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

# Configuramos el estilo del gráfico
plt.figure(figsize=(8, 4))
sns.histplot(df['price'], bins=30, kde=True, color='skyblue')

# Títulos y etiquetas
plt.title('Distribución de Precios del Catálogo')
plt.xlabel('Precio')
plt.ylabel('Frecuencia')

# Mostramos el gráfico
plt.show()

# Guardamos el resultado final limpio en un nuevo archivo CSV
df.to_csv('catalogo_procesado_final.csv', index=False)

print("¡Archivo exportado con éxito como 'catalogo_procesado_final.csv'!")